const loadHome = () => {
  const content = document.getElementById('content');
  const header = document.createElement('h1');
  header.setAttribute('class', 'home-header mt-5 ml-5 mb-5 text-center');
  header.textContent = 'Be yourself, enjoy your meals';
  content.appendChild(header);
  const container = document.createElement('div');
  container.setAttribute('class', 'container');
  content.appendChild(container);
  const row = document.createElement('div');
  row.setAttribute('class', 'row');
  container.appendChild(row);
  const colOne = document.createElement('div');
  colOne.setAttribute('class', 'col');
  row.appendChild(colOne);
  const parOne = document.createElement('p');
  parOne.setAttribute('class', 'par-one');
  parOne.textContent = 'Cheesecake';
  colOne.appendChild(parOne);
  const imgOne = document.createElement('img');
  imgOne.setAttribute('src', 'https://images.unsplash.com/photo-1524351199678-941a58a3df50?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1051&q=80');
  imgOne.setAttribute('class', 'home-img');
  colOne.appendChild(imgOne);

  const colTwo = document.createElement('div');
  colTwo.setAttribute('class', 'col');
  row.appendChild(colTwo);
  const parTwo = document.createElement('p');
  parTwo.setAttribute('class', 'par-one');
  parTwo.textContent = 'Muffin';
  colTwo.appendChild(parTwo);
  const imgTwo = document.createElement('img');
  imgTwo.setAttribute('src', 'https://images.unsplash.com/photo-1590759668580-b9fc6e734ce3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80');
  imgTwo.setAttribute('class', 'home-img');
  colTwo.appendChild(imgTwo);

  const colThree = document.createElement('div');
  colThree.setAttribute('class', 'col');
  row.appendChild(colThree);
  const parThree = document.createElement('p');
  parThree.setAttribute('class', 'par-one');
  parThree.textContent = 'Cake';
  colThree.appendChild(parThree);
  const imgThree = document.createElement('img');
  imgThree.setAttribute('src', 'https://images.unsplash.com/photo-1464941913535-1f37bfb72880?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80');
  imgThree.setAttribute('class', 'home-img text-center');
  colThree.appendChild(imgThree);
};
export default loadHome;
